### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by herp-a-derp** [yiffparty/tracker#12]
Heyo, I'm not sure what backend language you're using, but is there any chance you need help with anything? I can do good python, crappy JS, low level C and probably most other stuff with varying levels of mediocrity. I also have a patreon scraper of my own (under a different github acct), so there's that, too.

Oh, also, if you're noticing some bot traffic recently, that's probably also me (I'm doing a once-over archive). It'll be pretty spread out via a distributed RPC system, tho.

**Comment by kubotah** [comment]
Thank you for the offer, but we're not looking for any additional programming help at the moment. Though you're more than welcome to open issues regarding bugs you find or improvement suggestions.

**Comment by herp-a-derp** [comment]
Would a list of post attachment URLs that are failing due to 404 or similar be of interest?

On the other hand, that'd probably be pretty easy to pull from server logs.

**Comment by kubotah** [comment]
I'm not aware of any attachment 404 issues, but yes, that would be helpful if you've found any.
