### ISSUE TITLE
Importer broken

### ISSUE THREAD

**Issue by tahsinahmed2** [yiffparty/tracker#14]
I cant upload content to Yiff.party because it fails on the login

**Comment by kubotah** [comment]
Could you please confirm if you are able to log in normally to Patreon on their website? I am not seeing any issues with the importer, so continued errors are likely account-related.

**Comment by tahsinahmed2** [comment]
Yes it works on Patreon but i will test the importer tomorrow again because now i cant because of the many attempts block


________________________________
Von: kubotah <notifications@github.com>
Gesendet: Freitag, 11. August 2017 19:23
An: yiffparty/tracker
Cc: tahsinahmed2; Author
Betreff: Re: [yiffparty/tracker] Importer broken (#14)


Could you please confirm if you are able to log in normally to Patreon on their website? I am not seeing any issues with the importer, so continued errors are likely account-related.

**Comment by tahsinahmed2** [comment]
It is still broken. when i create a new account it working on the first time and on the second time it is again broken.
![unknown 2](https://user-images.githubusercontent.com/30934904/29252772-ba337e62-806d-11e7-99ce-aede419d273a.png)

**Comment by bui** [comment]
Is this still an issue? @tahsinahmed2

**Comment by tahsinahmed2** [comment]
No, only sometimes with my old account because of the recaptcha.

Recepcha support would be great.



________________________________
Von: Bui <notifications@github.com>
Gesendet: Donnerstag, 28. September 2017 15:36
An: yiffparty/tracker
Cc: tahsinahmed2; Mention
Betreff: Re: [yiffparty/tracker] Importer broken (#14)


Is this still an issue? @tahsinahmed2<https://github.com/tahsinahmed2>
