### ISSUE TITLE
Image download issue

### ISSUE THREAD

**Issue by Muad3D** [yiffparty/tracker#16]
When saving .jpg images from posts through "post file" they appear as genuine .jpg files but no application can open them due to "header reading" issue.
Worked before and only surfaced recently, in the last few weeks, months.
![b17f81547ceb11e1d24a23463313dab3](https://user-images.githubusercontent.com/32208235/30764346-fd9ed06c-9fd9-11e7-8e53-c1b280622cd1.png)

**Comment by bui** [comment]
File works fine on my machine, using HoneyView. Either your download is corrupt or IrfanView just doesn't like how that JPEG was built, which I can do nothing about as the file's bytes match those received from Patreon.
