### ISSUE TITLE
"Unknown Error" when uploading artists "Shared Files" content

### ISSUE THREAD

**Issue by G-Birkin** [yiffparty/tracker#18]
Every time I try to upload a file to the "Shared Files" section of any artist, it aways give me the message "Unknown error occurred, please try again." appearing next to the upload button

![image](https://user-images.githubusercontent.com/20481101/31633834-5c56a6a6-b2a0-11e7-93cb-44beaef0ab26.png)

**Comment by bui** [comment]
Fixed
