### ISSUE TITLE
Add scraping of comment section

### ISSUE THREAD

**Issue by pleyar** [yiffparty/tracker#3]
Some artists tend to post their links to comments, which is not covered by Yiff.party's fetching

**Comment by kubotah** [comment]
Possible, but then there's the question of fetching *new* comments. I'm aware of some creators who use one post to post external links via the comments every month or whatever.

I suppose the "rescan" suggestion from #2 could also fetch new comments.

**Comment by pleyar** [comment]
I think it would be more than sufficient if it was made on per-request basis. It should not automatically scrap them, neither should automatically updated for the watched ones.

Press a button to fetch the comments, the request will get queued up for the next user fetching and scraped. If out of date or links got expired, just press the button once more. In case of Pay-in Advance patreons, it should be added to a special queue that will get resolved only after the fetching tool gets the primary tasks done (fetching new patreon posts).

**Comment by bui** [comment]
all done
