### ISSUE TITLE
Categories system tweak

### ISSUE THREAD

**Issue by furandose** [yiffparty/tracker#4]
I think current categories system should be tweaked better. Currently it lacks fundamental tags. Primo - artists should be divided by gender categories (what gender or combination they mostly use). I propose two solutions:
1. staight (hetero), gay (homo), optional categories: both, other
2. male, female, herm and both or other
Second classification by type of work:
digital art, traditional art, cgi, animations, games, stories

I strongly encourage admin to check categories on furaffinity, deviantart, boorus (e621) etc and choose system best suiting YP.

**Comment by bui** [comment]
>staight (hetero), gay (homo), optional categories: both, other
>male, female, herm and both or other
These would be OK to apply for specific posts, but the type of content a creator can produce can be varied, which makes them unsuitable to be applied to creators in general.

>digital art, traditional art, cgi, animations, games, stories
This is possible. We will look into the possibility of adding a second set of tags.

**Comment by bui** [comment]
Done.

**Comment by furandose** [comment]
> These would be OK to apply for specific posts, but the type of content a creator can produce can be varied, which makes them unsuitable to be applied to creators in general.

I disagree. For example I don't like gay or male. I don't want to see it, but it's impossible to go through all creators to favorite somebody I enjoy.

**Comment by bui** [comment]
then find creators using other, more suitable websites (e621, furaffinity). yiff.party is not really meant to be used to find new creators

like I said, applying those tags to creators would be too broad for the majority of them
