### ISSUE TITLE
Corrupted rar downloads 

### ISSUE THREAD

**Issue by Aswzdxefc** [yiffparty/tracker#7]
Hello, some .rar downloads are corrupted and it seems that there is no feature permitting to report some posts with corrupted .rar !

**Comment by bui** [comment]
Can you please post an example creator + post ID/name?

**Comment by Aswzdxefc** [comment]
Creator : lapfox 
Post : Renard - SHOUNEN BASS! TURBO [Pre-Release Download] 
(the last post) 
the rar only weight 19.02 MB and is corrupted after downloading it

**Comment by Aswzdxefc** [comment]
Here is the link if it's quicker : https://yiff.party/254672
Last post has a corrupted rar.

Also this isn't the first time i'm seeing corrupted rar on the site ,although they aren't everywhere there is no way of making the site redownload the rar in case it is corrupted.

**Comment by bui** [comment]
I've implemented a Content-Length mismatch check for attachment downloads, to ensure this doesn't happen again.

As for the post in question - I would've refetched it, but this specific creator has enabled one of Patreon's new anti-scraping security features which we are currently investigating and attempting to resolve. Once it's fixed, the updater should be able to get the post without a problem.
